# Generated by Django 4.1.5 on 2023-01-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('prw_category', models.ImageField(default='static/category/default.webp', upload_to='static/category')),
                ('cat_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id_producer', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=60, verbose_name='производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=60, verbose_name='продукт')),
                ('prw_product', models.ImageField(default='static/product/default.webp', upload_to='static/product')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argo.producer', verbose_name='производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=60, verbose_name='размер листа')),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thicknes', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(verbose_name='ширина')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.product', verbose_name='продукт')),
                ('sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argo.sheet', verbose_name='размер листа')),
                ('thicknes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argo.thickness', verbose_name='толщина')),
                ('width', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argo.width', verbose_name='ширина')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id_sub', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=50)),
                ('prw_sub', models.ImageField(default='static/sub/default.webp', upload_to='static/sub')),
                ('sub_description', models.TextField(null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='argo.subcategory'),
        ),
    ]
