# Generated by Django 4.1.6 on 2023-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='power',
            field=models.CharField(default='-', max_length=20, verbose_name='мощность'),
        ),
    ]
