# Generated by Django 4.1.5 on 2023-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='width',
            name='width',
            field=models.CharField(max_length=60, verbose_name='ширина'),
        ),
    ]
