# Generated by Django 4.1.6 on 2023-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0002_variation_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_json',
            field=models.JSONField(default=11),
            preserve_default=False,
        ),
    ]
