# Generated by Django 4.1.6 on 2023-02-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0003_order_order_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0000000000', max_length=11),
        ),
    ]
