# Generated by Django 4.1.5 on 2023-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0003_product_prod_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(default='#000', max_length=20, verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='variation',
            name='default',
            field=models.BooleanField(default=False, verbose_name='по умолчанию'),
        ),
    ]
