# Generated by Django 4.1.5 on 2023-01-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0004_variation_color_variation_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='unit',
            field=models.CharField(default='шт', max_length=20),
        ),
    ]
