# Generated by Django 4.1.6 on 2023-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0004_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_json',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
