# Generated by Django 4.1.5 on 2023-02-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0007_currancy_alter_variation_sheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currancy',
            old_name='cur',
            new_name='cur_name',
        ),
        migrations.AddField(
            model_name='currancy',
            name='cur_value',
            field=models.IntegerField(default=1, verbose_name='значение'),
        ),
    ]
