# Generated by Django 4.1.5 on 2023-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0008_rename_cur_currancy_cur_name_currancy_cur_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
    ]
