# Generated by Django 4.1.5 on 2023-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0009_alter_variation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currancy',
            name='cur_value',
            field=models.FloatField(default=1, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
