# Generated by Django 4.1.6 on 2023-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0011_product_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('article', models.CharField(default='00000', max_length=7, primary_key=True, serialize=False)),
                ('user_order', models.CharField(default='аноним', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
        migrations.DeleteModel(
            name='Thickness',
        ),
        migrations.DeleteModel(
            name='Width',
        ),
    ]
