# Generated by Django 4.1.6 on 2023-02-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0012_order_delete_sheet_delete_thickness_delete_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='1', max_length=5)),
                ('matt', models.CharField(default='мат', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.order')),
                ('var_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.variation')),
            ],
        ),
    ]
