# Generated by Django 4.1.6 on 2023-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0013_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='matt',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
